# Generated by Django 4.2.4 on 2023-09-01 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('name_id', models.CharField(max_length=100, null=True)),
                ('salary', models.IntegerField(null=True)),
                ('position', models.CharField(max_length=100, null=True)),
                ('proj', models.DecimalField(decimal_places=3, max_digits=7, null=True)),
            ],
        ),
    ]
